language: node_js
node_js:
    - 7

cache:
    directories:
        - node_modules

script: npm run build
deploy:
    - provider: script
      skip_cleanup: true
      script: "./deploy.sh"
      on:
          branch: master
